### ISSUE TITLE
windows系统长时间休眠/睡眠后客户端被服务端踢掉了

### ISSUE THREAD

**Issue by WenSteven** [rongcloud/rongcloud-web-im-sdk-v2#11]
经过我们公司产品实践，发现客户端在长时间休眠后，即便有新的消息送达服务端，但客户端收不到任何消息，推测是服务端在检测心跳时，以为客户端挂掉了而导致客户端无效。官方有办法fix吗

**Comment by yuhongda0315** [comment]
Web 处理办法有两种：

1、休眠后，如果连接已断开，会触发状态监听网络不可用（NETWORK_UNAVAILABLE），此时可做重连处理

2、监控 Window `online`、`offline` ，当网络恢复后会触发 online 事件，在此时间中做重连处理，文档：[在线离线事件](https://developer.mozilla.org/zh-CN/docs/Web/API/NavigatorOnLine/Online_and_offline_events)

`备注`: `第二种需要考虑浏览器兼容性`

**Comment by WenSteven** [comment]
have fixed,thanks
