### ISSUE TITLE
获取历史私聊消息 中有群发消息 怎么解决？？？

### ISSUE THREAD

**Issue by zhoujianlin8** [rongcloud/rongcloud-web-im-sdk-v2#7]
const _self = this
        var conversationType = RongIMLib.ConversationType.PRIVATE; //私聊,其他会话选择相应的消息类型即可。
        var count = 20; // 每次获取的历史消息条数，范围 0-20 条，可以多次获取。
        RongIMLib.RongIMClient.getInstance().getHistoryMessages(conversationType, this.targetId, null, count, {
            onSuccess: function (list, hasMsg) {
                // console.log(list)
...

加我qq   1272195589

**Comment by yuhongda0315** [comment]
针对此类问题，可做以下排查：

1、每条消息中均有 conversationType ，枚举值请查看 [会话类型说明](https://www.rongcloud.cn/docs/web.html#conversation)，如果 conversationType 均为 `私聊` 请按第二步排查，如果 conversationType 部分为 `群聊`，部分为 `单聊` ，请按第三步排查

2、发送消息 ( sendMessage ) 时 conversationType 需要指定，此时类型是否按会话类型指定了不同值？

3、消息监听返回消息是不区分会话的，需要按区分 `会话 + targetId` 展示消息, 是否存在获取单聊历史消息时同时收到了群组消息导致的？

回复太不及时，但依然把排查思路列出来，方便其他开发者排查问题
