### ISSUE TITLE
啥时候能支持下小程序

### ISSUE THREAD

**Issue by surethink** [rongcloud/rongcloud-web-im-sdk-v2#8]
比较了下，融云的IM还是很靠谱的，遗憾的是其它几家已经支持微信小程序，而融云还不支持，貌似有个小程序版本还要收钱，还是期待能开源吸引更多的人用，你们赚大家用户量的钱，没必要靠sdk收钱提高门槛，得不偿失。个人意见，轻拍，哈

**Comment by yuhongda0315** [comment]
感谢反馈，融云是支持在微信小程序中提供 IM 能力的，可移步官网查看开通方式：[https://www.rongcloud.cn/product/miniprogram#product-features](https://www.rongcloud.cn/product/miniprogram#product-features)
 
关于付费，如您所说，付费确实是为了增加一定门槛，但主要目的是为了降低支持成本，抽身更多时间来做更多产品研发，服务更多开发者，还望理解

欢迎使用融云音视频、IM 相关产品～
